### ISSUE TITLE
Εκφώνηση του 25ος ΠΔΠ B' Φάση Λυκείου Οι μυστικοί αριθμοί (scidinner)

### ISSUE THREAD

**Issue by bettypan-epanomi** [pdp-archive/pdp-archive.github.io#101]
Μέσα στην εκφώνηση του προβλήματος του 25ου ΠΔΠ B' Φάση Λυκείου Οι μυστικοί αριθμοί (scidinner) υπάρχει αυτό :

" Πρόβλημα

Δοθείσης της γεωγραφίας της λίμνης και του ισοδύναμου υψομέτρου απορροών, να βρείτε το πλήθος των ενοποιημένων περιοχών που δεν πλημμυρίζουν. " 

Το κείμενο αυτό ανήκει στην εκφώνηση άλλου προβλήματος ( του Karla )

**Comment by Dim131** [comment]
Έχεις δίκιο. Ευχαριστούμε πολύ.
