### ISSUE TITLE
30ος Β φάση Γυμνασίου - Τα κάλαντα

### ISSUE THREAD

**Issue by stratigis78** [pdp-archive/pdp-archive.github.io#108]
Αγαπητοί μας κύριοι,

Στην βέλτιστη λύση σας, θα ήθελα να ρωτήσω κατά πόσο είναι απαραίτητο να έχουμε διπλάσιες θέσεις στο πίνακα.
Μήπως αν αλλάζαμε λίγο τον αλγόριθμο μπορούσαμε να χρησιμοποιήσουμε Ν+1 θέσεις; 
Παρακάτω δείχνω μια εκδοχή που νομίζω τρέχει σωστά:
int main()
{
    ios_base::sync_with_stdio(0);
    cin.tie(0);
    freopen( "kalanta.in", "r", stdin );
    freopen( "kalanta.out", "w", stdout );
    cin >> n;
    int cumsum[n+1];
    cumsum[0]=0;
    for (i=1; i<n+1; i++){
        cin >> sum;
        cumsum[i]=cumsum[i-1]+sum;
    }
    mn = cumsum[n]+1;
    while (front1 < n+1){
        currentsum = cumsum[front1] - cumsum[rear-1];
        if (abs(cumsum[n] - 2*currentsum) < mn){
            mn = abs(cumsum[n] - 2*currentsum);
        }
        if (cumsum[n] - 2*currentsum > 0){
            front1++;
        }
        else{
            rear++;
        }
    }
    cout << mn;
    return 0;
}
Ευχαριστώ.
Στράτης Περουτσέας

**Comment by Dim131** [comment]
Γεια σου Στρατη,

Ευχαριστούμε για το σχόλιο.

Δεν είναι απαραίτητο να έχεις 2Ν στοιχεία. Μπορείς να φτιάξεις μία συνάρτηση a(x) που επιστρέφει A[x] αν το x είναι μικρότερο ή ίσο N και x - N διαφορετικά. Μετά αλλάζεις όλα τα A[i] με a(i).  Πρόσθεσα μία σημείωση στη λύση.

Άμα θέλεις να διαβάσεις το αρχείο πάνω από μία φορές, τότε μπορείς να το κάνεις και με σταθερή O(1) μνήμη. (Πώς? Δες τη σημείωση 2 για ένα hint).

Δημήτρης

**Comment by stratigis78** [comment]
Εμείς ευχαριστούμε για το χρήσιμο υλικό που έχετε ανεβάσει.
Στράτης
