### ISSUE TITLE
Statement 28ος ΠΔΠ B' Φάση Γυμνασίου Ο χαρταετός (kite)

### ISSUE THREAD

**Issue by bettypan-epanomi** [pdp-archive/pdp-archive.github.io#117]
Τα χρώματα της εικόνας της καλούμπας στο παράδειγμα είναι σε λανθασμένη σειρά και δεν ανταποκρίνονται στο αμέσως από κάτω κείμενο:
« Τότε, μπορεί να διαλέξει τρία κομμάτια, το πράσινο, το μωβ και το γαλάζιο, και να έχει συνολικά 20+3+10=33 μέτρα.»

**Comment by kbokis** [comment]
Ευχαριστούμε για την υπόδειξη. 
Πράγματι φαίνονται κάπως παράξενα τα χρώματα.

Επιπλέον να ελεγχθεί το text justification στα constrains.

**Comment by Dim131** [comment]
Ναι, τα χρώματα ήταν διαφορετικά από αυτά της εκφώνησης στο pdf. Νομίζω τώρα είναι εντάξει.

Ευχαριστούμε πολύ
