### ISSUE TITLE
26ος ΠΔΠ Γ' Φάση: Επισκευή δρόμου (roadwork) - Λύση

### ISSUE THREAD

**Issue by bettypan-epanomi** [pdp-archive/pdp-archive.github.io#131]
Στη "Λύση σε O(N^2)"
στο σημείου του κειμένου
 "Για παράδειγμα, για τα διαστήματα  {[1,4],[2,6],[8,10]}
 , η αναπαράσταση είναι η εξής: "

το "2" πρέπει να αντικατασταθεί από το "3".

**Comment by Dim131** [comment]
Ναι, έχεις δίκιο. Πρέπει να διορθώθηκε στο #133 .
Ενημέρωσέ μας αν βρεις κανένα άλλο λάθος.

Ευχαριστούμε πολύ
