### ISSUE TITLE
31ος ΠΔΠ Γ' Φάση Ελάχιστη απόσταση (shortpowtwo)

### ISSUE THREAD

**Issue by bettypan-epanomi** [pdp-archive/pdp-archive.github.io#134]
1. Το link του pdf είναι λάθος , όπως και το link για το pdf του "Τι πληρώνει το λαχείο (lottery)" (31ος, Γ')
2. Δεν υπάρχει σωστή διάταξη στο 1ο από τα Παραδείγματα αρχείων εισόδου – εξόδου

**Comment by Dim131** [comment]
Καλημέρα,
Για το 2., έχεις δίκιο. Διορθώθηκε με το #135 .
Το pdf στο 1. δεν είναι λάθος. Όλα τα προβλήματα της Γ'Φάσης έχουν το ίδιο pdf.
Ευχαριστούμε

**Comment by bettypan-epanomi** [comment]
Για το 1. συγγνώμη, δικό μου λάθος.
Εμείς ευχαριστούμε πολύ για όλο το archive.
