### ISSUE TITLE
29ος ΠΔΠ Γ' Φάση Ακολουθίες DNA (dnaseq): Λάθος σε Sample Testcase

### ISSUE THREAD

**Issue by radaiosm7** [pdp-archive/pdp-archive.github.io#174]
Στη δεύτερη σειρά του δεύτερου παραδείγματος εισόδου, το τελευταίο Α είναι ελληνικό (αντί για λατινικό όπως θα έπρεπε).

**Comment by Dim131** [comment]
Ναι έχεις δίκιο. Πρέπει να διορθώθηκε τώρα. 

Ευχαριστούμε. Άμα βρεις κάποιο άλλο λάθος ή κάτι δεν είναι ξεκάθαρο, ενημέρωσέ μας
