### ISSUE TITLE
Πρόβλημα με τον online judge για 33ΠΔΠ landfight

### ISSUE THREAD

**Issue by Stoveste** [pdp-archive/pdp-archive.github.io#182]
Καταρχήν, ευχαριστώ πολύ για τον judge, την έχω καταβρεί να λύνω προηγούμενα θέματα.
Δοκίμαζα στον 33ο ΠΔΠ γ’ φάση το landfight και νομίζω υπάρχει κάποιος λάθος με τα testcases 25-31. Για να είμαι σίγουρος έβαλα και την λύση που έχει αναρτηθεί και πάλι δεν τα περνούσε.
Ευχαριστώ.

**Comment by Dim131** [comment]
Καλησπερα, 
Ωραία που το βρίσκεις χρήσιμο. 
Είδα ότι τα testcases 25-31 δεν υπήρχαν. Τώρα πρέπει να είναι εντάξει (διορθώθηκαν και μερικά άλλα tasks). Δοκίμασα και την λύση του site και περνάει. Δοκίμασε και εσύ.
Συγγνώμη αν έχασες πολύ ώρα. 

Ο judge είναι ακόμα σε αρχικά στάδια και ενδέχεται να έχει και άλλα τέτοια προβλήματα. Αν εντοπίσεις κάποιο άλλο, πες μας. 

Ευχαριστούμε,
Δημήτρης
