### ISSUE TITLE
34ΠΔΠ Γ'φάση marbles Εκφώνηση

### ISSUE THREAD

**Issue by bettypan-epanomi** [pdp-archive/pdp-archive.github.io#200]
Στην εκφώνηση είναι λάθος το κείμενο κάτω από το "Αρχείο εξόδου" 
( επαναλαμβάνεται το κείμενο του αρχείου εισόδου)

**Comment by Dim131** [comment]
Έχετε δίκιο. Πρέπει να διορθώθηκε τώρα. Ευχαριστούμε πολύ! 

(Αν παρατηρήσετε τίποτα άλλο, πείτε μας)
