### ISSUE TITLE
Ο judge δεν λειτουργεί

### ISSUE THREAD

**Issue by doublemidi** [pdp-archive/pdp-archive.github.io#230]
Μένει το submission "on queue" για πάντα

**Comment by Dim131** [comment]
Ευχαριστούμε, και συγγνώμη για την αργοπορημένη απάντηση. Τώρα πρέπει να είναι εντάξει. 

Άμα το ξαναδείς ενημέρωσε μας!

**Comment by doublemidi** [comment]
> Ευχαριστούμε, και συγγνώμη για την αργοπορημένη απάντηση. Τώρα πρέπει να είναι εντάξει.
> 
> Άμα το ξαναδείς ενημέρωσε μας!

Τώρα βγάζει " execve("a.out"): Resource temporarily unavailable
Exited with error status 127 " ότι κώδικα και να δώσω. Δεν ξέρω αν έχω μόνο εγώ το πρόβλημα η όχι, το τσέκαρα και με incognito.

**Comment by Dim131** [comment]
Έκανα μία μικρή αλλαγή. Για δοκίμασε ξανά

**Comment by doublemidi** [comment]
Δουλεύει κανονικά τώρα
