### ISSUE TITLE
Λάθος sample input στο secretpaths (35th camp)

### ISSUE THREAD

**Issue by doublemidi** [pdp-archive/pdp-archive.github.io#261]
Το δεύτερο sample input einai:
```
8 7 1
3 5
8 4
1 6
2 8
1 8
8 3
7 3
B 5 3
A 3 8
B 2 7
B 1 4
A 8 1
B 1 4
B 6 3
```

ενώ θα έπρεπε να είναι (σύμφωνα με την επεξήγηση και το output)
```
8 7 1
3 5
8 4
1 6
2 8
1 8
8 3
7 3
B 5 3
A 3 8
A 3 8
A 2 4
B 2 7
B 1 4
A 6 7
```

**Comment by Dim131** [comment]
Έχει δίκιο, ευχαριστούμε! Συγγνώμη για την αργοπορημένη απάντηση. 
Άμα βρεις οτιδήποτε άλλο ενημέρωσέ μας (ή αν θέλεις, δοκίμασε να το διορθώσεις με ένα pull request)!
