### ISSUE TITLE
master branch

### ISSUE THREAD

**Issue by kbokis** [pdp-archive/pdp-archive.github.io#34]
Θέλω να κάνω branch στο master με όνομα 24-solution-c1 για να βάλω την πρώτη λύση γ φασης αλλά δεν έχω επιλογή create branch.

**Comment by kipoujr** [comment]
Αν κατάλαβα καλά, δε μπορείς να κάνεις create branch στο κυρίως repo.
Αυτό συμβαίνει ώστε να υπάρχει μεγαλύτερη ασφάλεια ότι κάθε τι που υποβάλουμε έχει ελεγθεί κι από δεύτερο άτομο. Επομένως αντί να μπορούμε να δημιουργούμε branches και να κάνουμε commits, τα κάνουμε αυτά σε τοπικό αντίγραφο του repo, και μετά κάνουμε pull request.
Αυτό το tutorial τα περιγράφει καλά. https://kbroman.org/github_tutorial/pages/fork.html
Ενημέρωσέ με αν λειτούργησε αυτή η λύση.

**Comment by kbokis** [comment]
Ok, έκανα pull request ...
