### ISSUE TITLE
tester.sh

### ISSUE THREAD

**Issue by kipoujr** [pdp-archive/pdp-archive.github.io#35]
(split από προηγούμενο issue του kbokis που ρωτούσε δύο πράγματα ταυτόχρονα)
Τρέχω το tester.sh αλλά οι χρόνοι δεν είναι αντιπροσωπευτικοί. Π.χ. στη γραμμική λύση μου βγάζει timeout σε 3 testcases
Χρησιμοποιεί απόλυτους χρόνους ή χρόνους απασχόλησης επεξεργαστή;

>   SOLUTION : loutraki_nlogn
>Test 9: timeout
>Test 14: timeout
>Test 15: timeout
 >  SOLUTION : loutraki_n
>Test 9: timeout
>Test 14: timeout
>Test 15: timeout

**Comment by Dim131** [comment]
Το tester.sh χρησιμοποιεί την εντολή timeout, που μάλλον μετράει wall-clock time. Προς το παρόν δεν είχαμε κάποιο πρόβλημα, αλλά αν θέλετε μπορείτε να προτείνετε κάποια εναλλακτική για [εδώ](https://github.com/pdp-archive/pdp-archive.github.io/blob/master/source_code/utils/test_functions.sh#L23).

Κάποιες ερωτήσεις:
 1. Έχετε βάλει το σωστό timelimit (2 secs);
 2. Η ενδεικτική λύση περνάει; 
 3.  Μπορώ να δω τον κώδικα;

**Comment by kbokis** [comment]
@Dim131 
1) δεν έχω αλλάξει timelimit (1 δευτερόλεπτο δεν ήταν το όριο για τα προβλήματα;) με 10^6 * 10 ενέργειες.
2) δεν δοκίμασα την ενδεικτική λύση. Παίζω με τον 24ο PDP και αν δεν κάνω λάθος έχει λύσεις διαγωνιζομένων που δεν ήταν πάντα σωστές...
3) Τον έκανα ήδη pull αλλά τον παραθέτω πιο κάτω. Πρόκειται για το 1ο πρόβλημα της Γ φάσης του 24ου ΠΔΠ (Λουτράκι)

```c++
#include <bits/stdc++.h>

using namespace std;

#define MAXN	int(1e6)
#define OFFSET	int(1e5)

int N, ans;
bool hidden[MAXN+1];		//αληθές αν το ξενοδοχείο κρύβεται
int X[2*OFFSET+1],Y[2*OFFSET+1];//αριθμός του πρώτου ξενοδοχείου στην x ή y συντεταγμένη
pair<int,int> hotel[MAXN+1];
#define	xx	first
#define	yy	second

void hide_hotel(int i){//κρύψε ένα ξενοδοχείο που έχει υπολογιστεί παλιότερα.
	if(!hidden[i]){
		ans--;//δεν είναι πιά μέρος της απάντησης εφόσον κρύφτηκε από άλλο
		hidden[i] = true;
	}
}

int main() {
#ifdef CONTEST
	freopen("loutraki.in","r",stdin);
	freopen("loutraki.out","w",stdout);
#endif
	scanf("%d", &N);
	for(int x,y,i=1; i<=N; ++i){
		scanf("%d%d",&x,&y);
		x+=OFFSET; y+=OFFSET; //μετέτρεψε σε θετικούς
		hotel[i] = {x,y};
		int visibility = 0;
		
		//θα κρύψουμε κάποιο προηγούμενο ξενοδοχείο με το ίδιο x?
		if(X[x]){//υπάρχει ξενοδοχείο με το ίδιο x
			if(y < hotel[X[x]].yy){	//ναι, θα κρύψουμε το X[x]
				hide_hotel(X[x]);
				X[x] = i;
				visibility++;
			}
		} else {//είμαστε το πρώτο ξενοδοχείο με αυτό το x
			X[x] = i;
			visibility++;
		}
		
		if(Y[y]){
			if(x < hotel[Y[y]].xx){
				hide_hotel(Y[y]);
				Y[y] = i;
				visibility++;
			}
		} else {
			Y[y] = i;
			visibility++;
		}
		
		if(visibility<2)//δεν έχουμε ορατότητα και από τις δύο πλευρές
			hidden[i] = true;
		else		//ναι έχουμε ορατότητα. Αύξησε την απάντηση μας
			ans++;
	}
	printf("%d\n", ans);
	return 0;
}
```

**Comment by Dim131** [comment]
1. Για το Λουτράκι το limit είναι 2 δευτερόλεπτα. Δείτε [εδώ](https://pdp-archive.github.io/24-PDP/c-loutraki-statement). Δεν ξέρω αν θα είναι αρκετό, αλλά αξίζει να δοκιμάσετε. 
 2. Οι λύσεις μπορεί να μην είναι σωστές αλλά σε αυτή την περίπτωση [είναι](https://drive.google.com/file/d/1nOQifEj7wU1iK86e9leW0Akmj-Ygtrjw/view).
 3.  Ο κώδικας μου φαίνεται εντάξει, άρα ας δούμε αν δουλεύει το 1 (και μετά δοκιμάστε το 2). 

Ευχαριστούμε για το pull request. Φαίνεται ότι ξεκινήσατε να δουλεύετε στο master πριν μπει ο 24ος και γι'αυτό έχετε κάποια conflicts. Άμα χρειάζεστε βοήθεια να τα κάνετε resolve, πείτε μου

**Comment by kbokis** [comment]
Έβαλα 2 δευτερόλεπτα και πέρασε η γραμμική και η μία από τις δυο O(NlogN). Τη δεύτερη O(NlogN) θα την ψάξω και αλλο, προφανώς κάτι μου ξέφυγε.

Τα conflicts πρέπει να λύθηκαν, έκανα pull από το ενημερωμένο master και έκανα τις τροποποιήσεις μετά.

Θα περιμένω προτάσεις /reviews για να κάνω αλλαγές και θα περάσω και μερικές λύσεις διαγωνιζομένων.

**Comment by Dim131** [comment]
Καμία φορά οι NlogN λύσεις δεν περνάνε για Ν = 10^6. Δεν πειράζει άμα δεν τα περνάει όλα. 

Ωραία, θα το κοιτάξω ή εγώ ή ο kipoujr και θα σας δώσουμε σχόλια. 

Να κλείσουμε αυτό το issue?

**Comment by kbokis** [comment]
Εκανα και άλλη λύση logn και είδα οτι είναι οριακο αν περασει ή δεν περάσει ανάλογα με την υλοποίηση (π.χ. το sort υπερτερει του set). Οπότε όλα καλά. Μπορείτε να κλείσετε το issue.
