### ISSUE TITLE
Το tester.sh εμφανίζει πολλά warnings

### ISSUE THREAD

**Issue by kipoujr** [pdp-archive/pdp-archive.github.io#42]
Το tester.sh εμφανίζει warnings επειδή δεν αξιοποιούμε τις τιμές που επιστρέφει scanf, η freopen, κλπ.
Χρειαζόμαστε ένα πιο λακωνικό flag στο compile για να επικεντρωνόμαστε πιο εύκολα στα testcases και μόνο.

**Comment by Dim131** [comment]
Η εντολή είναι [εδώ](https://github.com/pdp-archive/pdp-archive.github.io/blob/master/source_code/utils/test_parser.cc#L19). Εμένα δεν μου εμφάνιζε κανένα warning μέχρι στιγμής, αλλά μπορούμε να προσθέσουμε -w αν θέλεις

**Comment by kipoujr** [comment]
Ίσως έχει να κάνει με την έκδοση του g++ που το τρέχει; Σε κάθε περίπτωση πρόσθεσα τα flags για όσους τραβάνε το ίδιο πρόβλημα με εμένα (κάνω commit σε λίγο).
