### ISSUE TITLE
Tester.sh και testcases

### ISSUE THREAD

**Issue by kipoujr** [pdp-archive/pdp-archive.github.io#46]
Το tester.sh θα μπορούσε να κατεβάζει μόνο του τα testcases, να τα αποσυμπιέζει/τρέχει/διαγράφει. Διότι νομίζω πολύ από εμάς βαριόμαστε να το τρέξουμε λόγω της μεγάλης διαδικασίας, ή στην καλύτερη περίπτωση ξεχνάμε να διαγράψουμε τα testcases στο τέλος.
Δηλαδή στο task να δίνουμε link ιντερνετικό αντί κανονικό. Ίσως να διατηρούμε κι ένα tester_offline παράλληλα απλώς.

**Comment by Dim131** [comment]
Είναι πολύ καλή ιδέα αυτή (η διαγραφή δεν χρειάζεται). Πρέπει να μαζέψουμε όλα τα testcases μαζί και να βρούμε έναν server να τα βάλουμε. Στο github δεν χωράνε αν θυμάμαι καλά και νομίζω το drive δεν πάει πολύ καλά με το wget.

**Comment by kipoujr** [comment]
Αφήνω αυτό για μελλοντική χρήση, λέει ότι μπορούμε να κάνουμε wget στο drive, αρκεί να ξεχωρίζουμε ανάμεσα σε <100 MB και >100 MB αρχεία.
