### ISSUE TITLE
[24pdp_c2_minpali] Add constraint or not? That is the question.

### ISSUE THREAD

**Issue by kbokis** [pdp-archive/pdp-archive.github.io#55]
Στο πρόβλημα minpali (24pdp,c2) δεν υπάρχει στην εκφωνηση αναφορά για το σύνολο τιμών των χαρακτήρων της συμβολοσειράς. Τα παραδειγματα εκφωνησης ειναι ολα με μικρους αγγλικους χαρακτηρες. Στα testcases υπαρχουν και αριθμοί. 
Στη λύση με brute force, KMP ή Z δεν υπάρχει θέμα γιατί γίνεται σύγκριση ακεραίων.
Στη λύση rabin-karb όμως έχει σημασία για την επιλογή του σταθερού παράγοντα.

Δεν νομίζω ότι το νόημα ήταν να γίνει compression των χαρακτήρων εισόδου και υπολογισμός της σταθεράς αυτής μετά το compression.

**Comment by kipoujr** [comment]
Αν θυμάμαι καλά είναι standard σε διαγωνισμούς όταν δε λες τι χαρακτήρες μπορεί να εμφανιστούν, να χρησιμοποιείς απλά αλφάβητο μήκους 256 στον rabin karp.
Ή το άλλο το κόλπο που εγώ δε χρησιμοποιούσα βέβαια, που θεωρείς αλφάβητο μήκους 256+smallRandom (hardcoded στο πρόγραμμα) και unsigned long long, και δεν κάνεις καν mod, το αφήνεις να γίνεται μόνο του με το overflow.

Συμφωνώ ότι δεν υπάρχει λόγος για υπολογισμό αργότερα, απλά χρησιμοποίησε το άνω όριο 256 :)

Αν είναι οκ η απάντηση, κλείσε το issue, αλλιώς συνεχίζει η συζήτηση.

**Comment by kbokis** [comment]
Οκ απλά θα το επισημάνω ότι δεν πρέπει να γίνει υπόθεση από το διαγωνιζόμενο και να την πατήσει.
