### ISSUE TITLE
Το TASK του symstr έχει τα στοιχεία του mntsea 

### ISSUE THREAD

**Issue by Dim131** [pdp-archive/pdp-archive.github.io#58]
Δες [εδώ](https://github.com/pdp-archive/pdp-archive.github.io/blob/master/source_code/code/31-PDP/symstr/TASK)

**Comment by kipoujr** [comment]
Το έστρωσα στο drive, κι επίσης άλλαξα ότι χρειαζόταν από τα αρχεία μας (νέο λινκ, αλλαγή στο TASK)
Fixed με το commit https://github.com/pdp-archive/pdp-archive.github.io/commit/ca472bcd9f449be359feaafcffb38423110ba98a
