### ISSUE TITLE
Links για προαπαιτούμενο/περαιτέρω διάβασμα

### ISSUE THREAD

**Issue by kipoujr** [pdp-archive/pdp-archive.github.io#76]
Τώρα που προσθέσαμε τα tags, μήπως θα έπρεπε να μπαίνει αυτόματα ένα header που να τους λέει τι να διαβάσουν;
Και το header αυτό να περιλαμβάνει πάντα και το link για πολυπλοκότητα;

**Comment by Dim131** [comment]
Δεν είμαι σίγουρος ότι κατάλαβα καλά, αλλά υπάρχει το εξής θέμα: διαφορετικές λύσεις μπορεί να θέλουν να ξέρει κανείς διαφορετικά πράγματα. Επίσης δεν είναι πάντα "και" αυτό που ενώνει τις γνώσεις των λύσεων (για παράδειγμα στο min-pali, δεν πρέπει να ξέρεις z-algorithm και kmp και manacher).

**Comment by kipoujr** [comment]
Σωστό, κακό θα κάνει στους μαθητές αν αυτοματοποιηθεί. Ας ζοριστούμε λίγο παραπάνω αν είναι να βγαίνει όμορφη δουλειά.
