### ISSUE TITLE
code.md

### ISSUE THREAD

**Issue by kbokis** [pdp-archive/pdp-archive.github.io#79]
Αν κάνουμε στο solution.md include κάποιο .cpp/.cc και υπάρχει το sequence "{%", το code.md προσπαθεί να το αντιστοιχίσει με το αντίστοιχο κλείσιμο και δεν το βρίσκει φυσικά χωρίς να μπορεί να πληροφορίσει που βρέθηκε το πρόβλημα.
Γιατί να υπάρχει `{%`? Έτυχε να υπάρχσει σε ένα debug `printf("{%lf ....}\n",...)` :)

Άρα η στις οδηγίες για τη συγγραφή κώδικα να το βάλουμε σαν απαγόρευση από τα cc/cpp ή να φτιάξουμε το code.md

**Comment by Dim131** [comment]
Είχαμε αυτό το πρόβλημα και με τον Βαγγέλη, αλλά δεν νομίζω ότι υπάρχει πολύ απλός τρόπος να το διορθώσουμε. Αν έχετε κάποια ιδέα, μπορείτε να δοκιμάσετε. 

Σε όλους τους κώδικες, μέχρι στιγμής, υπήρχε ένα τέτοιο πρόβλημα και δεν ήταν αναγκαίο. 

Πρόσθεσα μία μικρή σημείωση στο README: https://github.com/pdp-archive/pdp-archive.github.io/pull/80
Πείτε μου αν έχετε σχόλια.
