### ISSUE TITLE
31ος ΠΔΠ B' Φάση: Βουνό ή θάλασσα (mntsea)

### ISSUE THREAD

**Issue by stratigis78** [pdp-archive/pdp-archive.github.io#91]
Γεια σας!
Μήπως στη λύση με τίτλο "Αργή λύση - O(N2). Εισάγονται καινούργιες ιδέες που θα χρειαστούν για τη βέλτιστη λύση." χρειάζονται οι εντολές:
sumM[0] = 0
sumS[0] = 0
πριν την for (long i=1; i<=N; ++i) { ;
Ομοίως και σε παρακάτω λύσεις με την ίδια λογική.
Με εκτίμηση,
ΕΠ

**Comment by Dim131** [comment]
Καλησπέρα,

Στην συγκεκριμένη περίπτωση η `sumM `και `sumS` είναι global μεταβλητές, άρα θα αρχικοποιηθούν σε `0`. Επομένως δεν είναι ανάγκη να κάνουμε `sumM[0] = 0` και `sumS[0] = 0`. (Δες [εδώ](https://stackoverflow.com/questions/16015656/are-global-variables-always-initialized-to-zero-in-c) για αναφορές στο standard της C)

Ευχαριστούμε,
Δημήτρης

**Comment by synthels** [comment]
Να κάτι που δεν ήξερα για το C Standard! Ευχαριστούμε!

**Comment by stratigis78** [comment]
Ευχαριστώ πολύ.
