### ISSUE TITLE
32ος ΠΔΠ B' Φάση: Τα δύο καταστήματα (shops)

### ISSUE THREAD

**Issue by stratigis78** [pdp-archive/pdp-archive.github.io#92]
Γεια σας!
Μήπως στην τελευταία  προσέγγιση χωρίς χρήση cumulative sums αλλά με χρήση sliding window αντί για
 if(shopleft > K){
χρειάζεται 
 if( i > K){
;
Με εκτίμηση,
ΕΠ

**Comment by kipoujr** [comment]
Καλησπέρα φίλε μου.
Με συγχωρείς, δεν κατάλαβα σε ποια γραμμή του κώδικα αναφέρεσαι, με CTRL+F δε βρίσκω shopleft πουθενά.

**Comment by stratigis78** [comment]
Στον τελευταίο κώδικα 18η γραμμή:

#include <cstdio>
#include <algorithm>

const long MAXN = 2000000;
using namespace std;

long N, K, ans, A[MAXN+5], maxUpTo[MAXN+5];

int main() {
  freopen("shops.in","r",stdin);
  freopen("shops.out","w",stdout);
  scanf("%ld %ld", &N, &K);
  for(long i=1; i<=N; ++i) 
    scanf("%ld", &A[i]);

  for(long shopleft=0, i=1; i<=N-K; ++i){
      shopleft += A[i];
      if(shopleft > K){
      //το shopleft έχει άθροισμα Κ+1 διαδοχικών θέσεων. 
          //Αφαίρερε την παλιότερη.

**Comment by stratigis78** [comment]
Δες και αυτό με την ευκαιρία:
//Αφαίρερε την παλιότερη
Στο ίδιο σημείο.

**Comment by kipoujr** [comment]
Φαίνεται να έχεις δίκιο φίλε μου, θα το δω πιο προσεκτικά αύριο και θα το διορθώσω.
Σε ευχαριστώ πολύ.

**Comment by kipoujr** [comment]
Fixed in #

**Comment by stratigis78** [comment]
Εμείς ευχαριστούμε για το πολύτιμο υλικό που έχετε παραθέσει.
