### ISSUE TITLE
Ελέγχουμε ότι οι λύσεις σε pascal περνάνε τα testcases (και ποια)

### ISSUE THREAD

**Issue by Dim131** [pdp-archive/pdp-archive.github.io#98]
Τώρα που ο tester υποστηρίζει κώδικα σε pascal, μπορούμε να ελέγξουμε και να καταγράψουμε ποια testcases περνάει η κάθε λύση:

Συγκεκριμένα υπάρχουν τα εξής tasks (μέσα στο site και μερικά από τους 22-24 που δεν έχουμε προσθέσει ακόμα):
 * seti
 * domes
 * hydrogen
 * company
 * profit
 * sch
 * ensemble
 * xxx
 * aris
 * solar
 * scidinner
 * snow_run
 * karla
 * operators
 * function
 * twosqr
 * share

**Comment by kbokis** [comment]
25ος ΚΑΡΛΑ pascal ok
